# Generated by Django 2.2.25 on 2021-12-20 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuestBookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knit_message', models.CharField(max_length=140)),
                ('extra_message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 19, 22, 52, 21, 969058))),
            ],
        ),
    ]
